### ISSUE TITLE
rendering tmux splits glitch

### ISSUE THREAD

**Issue by milochadam** [christianparpart/contour#118] opened 2020-06-07 14:38 UTC
![tmux rendering glitch](https://user-images.githubusercontent.com/27895477/83971512-def31c00-a8db-11ea-9e37-c6546a5e106e.png)

#### contour log
```
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FT_Select_Charmap failed. Ignoring; invalid charmap handle
FontLoader: loading font "Fira Code" from "/usr/share/fonts/TTF/FiraCode-Regular.ttf", size=12, fallbacks=53
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FontLoader: loading font "Fira Code:style=bold" from "/usr/share/fonts/TTF/FiraCode-Bold.ttf", size=12, fallbacks=55
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FontLoader: loading font "Fira Code:style=italic" from "/usr/share/fonts/TTF/FiraCode-Regular.ttf", size=12, fallbacks=55
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FontLoader: loading font "Fira Code:style=bold italic" from "/usr/share/fonts/TTF/FiraCode-Regular.ttf", size=12, fallbacks=55
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FontLoader: loading font "emoji" from "/usr/share/fonts/TTF/Symbola.ttf", size=12, fallbacks=46
OpenGL type     : OpenGL
OpenGL renderer : AMD TAHITI (DRM 2.50.0, 5.4.43-1-MANJARO, LLVM 10.0.0)
OpenGL version  : 4.5
GLSL version    : 4.50 (450, 440, 430, 420, 410, 400, 330, 150, 140, 130, 120, 320 es, 310 es, 300 es, 100)

Invalid output sequence: CSI 0 c. 
Unsupported output sequence: CSI 1337 n.
```
Last two lines log lines appear when starting tmux in contour.

My tmux config:
https://github.com/milochadam/dotfiles/blob/e78057efdb8487869760b0702476010397b23efb/tmux/.tmux.conf

Let me know if you need anything else :)

**Comment by christianparpart** [comment] 2020-06-07 15:01
This is an interesting one. That isn't nice indeed. Many thanks for the early tests, I will try to reproduce this.

**Comment by christianparpart** [comment] 2020-06-23 09:12
`CSI 0 c` is "`CSI Ps c`  Send Device Attributes (Primary DA).", which definitely must be implemented (basic building blocks there)

I am not so sure where `CSI 1337 n` is coming from. The `1337` hints you are on an OS/X and used to use iTerm2? Because they seem to have introduced quite some OSCs with the identifier 1337, but your screenshot is saying "manjaro". Do you happen to know where where this `CSI 1337 n` is coming from? Nevertheless, I'm investigating on tmux now. Thanks for your patience. :)

**Comment by milochadam** [comment] 2020-06-25 06:48
I'm not sure where that comes from nor do I know how to check that unfrtunately.
I'm using Manjaro and Windows (only managed to compile it on Manjaro though) and I ran it from Gnome Terminal 3.36.2.

There glitches seem the same (or similar). Another example:
![tmux rendering glitch3](https://user-images.githubusercontent.com/27895477/85669846-8a63e500-b6c0-11ea-8313-e6bc5725bc08.png)

**Comment by christianparpart** [comment] 2020-06-30 22:13
@milochadam I am pretty sure that with the last commit I was fixing the tmux glitches you had, too. This is on `wip` branch (bare in mind, never `git pull` on git branch, but do `git fetch && git reset --hard origin/wip` if you have **already** checked out `wip` branch before. I'll merge to `master` if you can confirm it was fixing it for you, too.

**Comment by milochadam** [comment] 2020-07-01 06:21
Unfortunately the problem still persists. I also tried running without .tmux.conf but with no avail.

**Comment by christianparpart** [comment] 2020-07-01 07:44
> Unfortunately the problem still persists. I also tried running without .tmux.conf but with no avail.

Hey, many thanks. But just to be sure, which branch are you using, and what's your TERM environment variable outside of tmux and what tmux version are you having? (`tmux -V`).

**Comment by milochadam** [comment] 2020-07-01 08:37
I'm on wip branch:
```
HEAD is now at b218d0f adds missing headers
```
echo $TERM:
```
xterm-256color
```
tmux -V:
```
tmux 3.1b
```

**Comment by christianparpart** [comment] 2020-07-10 12:09
Accidentally closed by Github because of a git commit. hmmm....

**Comment by christianparpart** [comment] 2021-03-24 21:53
I think we can close this now. In my local tests it's working. Please reopen if you are still having any issues otherwise. :-)

**Closed by christianparpart** 2021-03-24 21:53 UTC
Labels: bug
