### ISSUE TITLE
Terminal flickers

### ISSUE THREAD

**Issue by sonulohani** [christianparpart/contour#124] opened 2020-07-03 14:45 UTC
## Description

The contour terminal flickers.

## Environment

- Contour Version or Git commit hash: ab6f636fc1812d572850100f5092af746f82e030
- Operating System (name / distribution / version): Windows 10 2004
- Contour configuration: Default configuration
- TERM environment variable: NA
- Compiler version: Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e
-

## Steps to Reproduce

Just Launch contour and see the flickers. See the screenshot for more info.

![flicker](https://user-images.githubusercontent.com/2958681/86479530-f8b44180-bd69-11ea-8222-edf058a6076f.png)
![flicker2](https://user-images.githubusercontent.com/2958681/86479534-fb169b80-bd69-11ea-9e83-1250268f933b.png)
![image](https://user-images.githubusercontent.com/2958681/86479750-62cce680-bd6a-11ea-968a-26fe6bb99f39.png)

**Comment by sonulohani** [comment] 2020-07-03 14:46
BTW I am the guy from your stream if you remembered. :-)

**Comment by christianparpart** [comment] 2020-07-04 06:55
Let's meet in stream or even discord on Monday for that. Thanks for the report. :)

**Comment by sonulohani** [comment] 2020-09-20 14:54
Hi @christianparpart I can't verify whether this issue got fixed or not because I abandoned windows os. Now I am full time user of PopOs and in PopOs this application rocks. Didn't got any issue yet.

**Comment by christianparpart** [comment] 2020-09-20 14:58
Hey, @sonulohani , thanks for keeping me posted. And welcome to the Linux world.

I am not closing this ticket just yet because part two weeks I have been using Windows exclusively when touching contour (actually, for packaging reasons, automatic installer she getting the windows version in better shape).

I hope I can address some more windows related stuff and eventually will also close this ticket here soon.

Chris.

**Comment by christianparpart** [comment] 2021-03-24 12:25
I'm closing this for now. I think this isn't reproducible anymore (not for me). Let's reopen if it happens again.

**Closed by christianparpart** 2021-03-24 12:25 UTC
Labels: GL terminal view, bug

**Comment by sonulohani** [comment] 2021-03-24 12:37
Lets keep it closed. The application is working fine.
